#!/usr/bin/env python3
"""Generate web_ui.h from data/index.html.
Run once after any change to index.html (or to bump VERSION_MINOR),
then recompile and OTA-flash the firmware.
Usage: python3 tools/embed_html.py
"""
import gzip, os, subprocess

# ── Version ───────────────────────────────────────────────────────────────────
VERSION_MAJOR = 12
VERSION_MINOR = 2   # bump manually for milestone releases
# Patch counter resets to 0 at each minor bump. Set VERSION_PATCH_BASE to the
# commit count at the bump commit so patch = HEAD_count - base.  Without this,
# each new series would inherit the old running count instead of starting at
# .0.  JS semver compare orders by minor first, so the OTA update gate sees
# 12.2.x > 12.1.y regardless of patch.
# 12.2: the bug-sweep series — calibration sync, vib inStack latch, OTA reboot
# overlay, auth reconnect, TOF signal smoothing.
VERSION_PATCH_BASE = 168
# ─────────────────────────────────────────────────────────────────────────────

root = os.path.join(os.path.dirname(os.path.abspath(__file__)), '..')
src  = os.path.join(root, 'data', 'index.html')
dst  = os.path.join(root, 'data', 'web_ui.h')

# Git info
def git(cmd):
    try:
        return subprocess.check_output(cmd, cwd=root, stderr=subprocess.DEVNULL).decode().strip()
    except Exception:
        return '?'

count  = git(['git', 'rev-list', '--count', 'HEAD'])
commit = git(['git', 'rev-parse', '--short', 'HEAD'])
try:
    patch = max(0, int(count) - VERSION_PATCH_BASE)
except ValueError:
    patch = count  # git unavailable — leave whatever git() returned
version = f'{VERSION_MAJOR}.{VERSION_MINOR}.{patch}'

# Source metrics — counted across the project's hand-written files so the
# About screen reports an accurate, build-fresh figure.  web_ui.h is the
# generated artifact (would double-count index.html) and is excluded.
SOURCE_FILES = [
    'AutoFOV_V12.ino', 'AutoFOV_V12_wifi.ino',
    'data/index.html', 'data/FreeSans7pt7b.h',
    'tools/build.sh', 'tools/drift-check.sh',
    'tools/flash_firmware_only.sh', 'tools/release.sh',
    'tools/embed_html.py',
]
sloc  = 0
sbytes = 0
for rel in SOURCE_FILES:
    full = os.path.join(root, rel)
    try:
        with open(full, 'rb') as fp:
            data = fp.read()
            sbytes += len(data)
            sloc   += data.count(b'\n') + (1 if data and not data.endswith(b'\n') else 0)
    except OSError:
        pass
skb = (sbytes + 512) // 1024     # round to nearest KB

with open(src, 'rb') as f:
    raw = f.read()

compressed = gzip.compress(raw, compresslevel=9)

out = []
out.append('// Auto-generated by tools/embed_html.py — do not edit manually.')
out.append('// Re-run the script whenever data/index.html changes, then recompile.')
out.append('#pragma once')
out.append('#include <pgmspace.h>')
out.append('')
out.append(f'#define BUILD_VERSION "{version}"')
out.append(f'#define BUILD_COMMIT  "{commit}"')
out.append(f'#define BUILD_SLOC    {sloc}')
out.append(f'#define BUILD_SKB     {skb}')
out.append('')
out.append(f'// {len(raw)} bytes raw  ->  {len(compressed)} bytes gzip')
out.append('static const uint8_t WEB_UI_HTML_GZ[] PROGMEM = {')
for i in range(0, len(compressed), 16):
    chunk = compressed[i:i+16]
    out.append('    ' + ', '.join(f'0x{b:02x}' for b in chunk) + ',')
out.append('};')
out.append(f'static const size_t WEB_UI_HTML_GZ_LEN = {len(compressed)};')

with open(dst, 'w') as f:
    f.write('\n'.join(out) + '\n')

print(f'v{version} ({commit})  |  html: {len(raw):,} -> {len(compressed):,} bytes  |  sloc: {sloc:,} ({skb} KB)')
