#!/usr/bin/env python3
"""Generate web_ui.h from data/index.html.
Run once after any change to index.html, then recompile and OTA-flash the firmware.
Usage: python3 tools/embed_html.py
"""
import gzip, os

root = os.path.join(os.path.dirname(os.path.abspath(__file__)), '..')
src  = os.path.join(root, 'data', 'index.html')
dst  = os.path.join(root, 'web_ui.h')

with open(src, 'rb') as f:
    raw = f.read()

compressed = gzip.compress(raw, compresslevel=9)

out = []
out.append('// Auto-generated by tools/embed_html.py — do not edit manually.')
out.append('// Re-run the script whenever data/index.html changes, then recompile.')
out.append('#pragma once')
out.append('#include <pgmspace.h>')
out.append(f'// {len(raw)} bytes raw  ->  {len(compressed)} bytes gzip')
out.append('static const uint8_t WEB_UI_HTML_GZ[] PROGMEM = {')
for i in range(0, len(compressed), 16):
    chunk = compressed[i:i+16]
    out.append('    ' + ', '.join(f'0x{b:02x}' for b in chunk) + ',')
out.append('};')
out.append(f'static const size_t WEB_UI_HTML_GZ_LEN = {len(compressed)};')

with open(dst, 'w') as f:
    f.write('\n'.join(out) + '\n')

print(f'web_ui.h: {len(raw):,} -> {len(compressed):,} bytes ({len(compressed)*100//len(raw)}% of original)')
